/**
 * Generate src/corpus-data.ts from the vendored canonical text.
 *
 * The Tanzil terms require the text be kept intact and attributed; the module
 * embeds the verse body verbatim (surah|ayah|text lines, minus Tanzil's
 * comment footer, which is reproduced in the header comment).
 */
import { readFileSync, writeFileSync } from "node:fs";

const raw = readFileSync("vendor/quran-uthmani-current.txt", "utf8");
const lines = raw.split("\n").map((l) => l.replace(/\r$/, "")).filter((l) => l && !l.startsWith("#"));
if (lines.length !== 6236) throw new Error(`expected 6236 verse lines, got ${lines.length}`);

const body = lines.join("\n");
const out = `/**
 * Qur'an text: Tanzil Uthmani (https://tanzil.net), snapshot 2026-07-11.
 * GENERATED by tools/gen-corpus-module.ts: do not edit.
 *
 * Tanzil terms of use: the text is carried intact, verse by verse, with this
 * attribution. Source: Tanzil Quran Text (Uthmani, version 1.x),
 * Copyright (C) 2007–2026 Tanzil Project, tanzil.net/download.
 */
export const CORPUS_LINES: string = ${JSON.stringify(body)};
`;
writeFileSync("src/corpus-data.ts", out);
console.log(`src/corpus-data.ts written (${(out.length / 1024).toFixed(0)} KiB)`);
